{% set version = "1.14.7-1" %}
{% set sha256 = "d9c8100fd5dcf41f7d4645263161d02ed5157414b32acac7a5d4ff984892954e" %}

package:
  name: ros-ros
  version: {{ version.split("-")[0] }}

source:
  url: https://github.com/ros-gbp/ros-release/archive/release/melodic/ros/{{ version }}.tar.gz
  sha256: {{ sha256 }}


build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - cmake
    - make  # [unix]
  host:
    - ros-conda-mutex * melodic
    - ros-conda-base
    - catkin_pkg
    - ros-catkin
  run:
    - ros-conda-mutex * melodic
    - ros-conda-base
    - ros-catkin
    - ros-mk
    - ros-roscreate
    - ros-roslib
    - ros-rosbuild
    - ros-roslang
    - ros-rosbash
    - ros-rosmake
    - ros-rosunit
    - ros-rosboost-cfg
    - ros-rosclean

test:
  commands:
    - test -f $PREFIX/share/ros/package.xml  # [unix]

about:
  home: http://www.ros.org/wiki/ROS
  summary: |
    ROS packaging system (Meta Package)
  description: |
    ROS packaging system
  license: BSD-3-Clause
  license_file: package.xml

extra:
  recipe-maintainers:
    - wolfv
    - lesteve
    - seanyen
